language: r
sudo: false
cache: packages
env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

r:
  - devel
  - release

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
